import pandas as pd
from groq import Groq
import os

def generate_ads():
    try:
        # Load the leads generated by the scraper
        if not os.path.exists("leads.csv"):
            print("❌ leads.csv not found! Running with dummy data for testing...")
            df = pd.DataFrame({
                "name": ["Test Pizza"], 
                "neighborhood": ["Downtown"], 
                "landmark": ["Central Park"]
            })
        else:
            df = pd.read_csv("leads.csv")

        api_key = os.getenv("GROQ_API_KEY")

        if not api_key:
            print("⚠️ No GROQ_API_KEY found. Using fallback text.")
            df['generated_ad'] = "Special offer for " + df['name'] + "! Visit us today."
        else:
            print("🚀 Groq API Key found. Generating Free AI ads using Llama 3.1...")
            client = Groq(api_key=api_key)
            
            ad_results = []
            for _, row in df.iterrows():
                try:
                    # Using the updated model: llama-3.1-8b-instant
                    chat_completion = client.chat.completions.create(
                        messages=[
                            {
                                "role": "system",
                                "content": "You are an elite local ad copywriter."
                            },
                            {
                                "role": "user",
                                "content": f"Write a punchy Facebook ad for {row['name']} in {row['neighborhood']}. Mention it is near {row['landmark']}. Include a 'Get Directions' CTA. Max 40 words.",
                            }
                        ],
                        model="llama-3.1-8b-instant", # NEW MODEL ID
                    )
                    ad_results.append(chat_completion.choices[0].message.content)
                except Exception as api_err:
                    print(f"⚠️ API Error on a row: {api_err}")
                    ad_results.append(f"Check out {row['name']} near {row['landmark']}!")
            
            df['generated_ad'] = ad_results

        # Save to the final file for the Dashboard
        df.to_csv("final_ads.csv", index=False)
        print("✅ Success! final_ads.csv created.")
        
    except Exception as e:
        print(f"❌ critical Error: {e}")
        # Create a basic file so the GitHub Action doesn't fail
        pd.DataFrame({"status": ["Error"], "msg": [str(e)]}).to_csv("final_ads.csv", index=False)

if __name__ == "__main__":
    generate_ads()
